#pragma once

#define WM_QUOTE_CHANGED  WM_USER + 4
#define WM_HOGA_CHANGED  WM_USER + 5
#define WM_ORDER_CHANGED  WM_USER + 6
#define WM_ACCOUNT_CHANGED  WM_USER + 7
#define WM_CHART_DATA_UPDATED  WM_USER + 8
#define WM_CHART_DATA_RECEIVED  WM_USER + 9
#define WM_CHART_DATA_ADDED  WM_USER + 10
#define WM_SYMBOL_LIST_RECEIVED  WM_USER + 11
#define WM_SYMBOL_MASTER_RECEIVED  WM_USER + 12
#define WM_QUOTE_RECEIVED  WM_USER + 12
#define WM_HOGA_RECEIVED  WM_USER + 12
#define WM_ORDER_UPDATE WM_USER + 13
#define WM_PASSWORD_CONFIRMED WM_USER + 14
#define WM_SERVER_MSG WM_USER + 15
#define WM_FUND_CHANGED WM_USER + 16